name: Generate Space Invaders animation

on:
  schedule:
    - cron: "0 */12 * * *"   # roda a cada 12 horas
  workflow_dispatch:           # permite rodar manualmente
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # ← ESSENCIAL, sem isso falha!
    steps:
      - name: Generate animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: LegabrieLp
          outputs: |
            dist/github-stats-invaders.svg?color_snake=cyan&color_dots=#0d1117,#0d1117,#0d1117,#0d1117,#0d1117

      - name: Push to branch invaders-output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: invaders-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
