name: Generate Space Invaders

on:
  schedule: # Roda automaticamente a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite rodar manualmente a qualquer momento

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      # Gera a animação da navezinha do Space Invaders atirando nos blocos
      - name: GitHub Invaders
        uses: jstrieb/github-stats-invaders@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Configura as cores para combinar com o seu tema Tokyonight
          bg_color: "#1a1b26"
          text_color: "#7aa2f7"
          grid_color: "#444b6a"
          l1_color: "#b4f9f8"
          l2_color: "#2ac3de"
          l3_color: "#7dcfff"
          l4_color: "#7aa2f7"

      # Salva a animação gerada na branch invaders-output
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: invaders-output
          # A ação jstrieb/github-stats-invaders gera o arquivo no diretório raiz por padrão
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
