name: Generate Pac-Man animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Generate Pac-Man
        uses: buluma/pacman-contribution-graph-action@main
        with:
          github_user_name: LegabrieLp
          gif_out_path: dist/pacman.gif

      - name: Push to pacman-output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: pacman-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
